accounts/urls.py
from django.urls import path
from . import views
from .views import get_csrf_token

app_name = 'accounts'

urlpatterns = [
    path(r'signup/', views.signup_view, name="signup"),
    path(r'login/', views.login_view, name="login"),
    path(r'login/get_csrf_token/', views.get_csrf_token, name="token"),
    path(r'logout/', views.logout_view, name="logout")
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path(r'', views.apiOverview , name="api"),
    path(r'task-list/', views.taskList , name="List"),
    path(r'task-create/', views.createTask, name="create")
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [     
    path(r'', views.article_list, name="list"),     # Raw string
    path(r'get/<id>/', views.article_one, name="getById"),
    path(r'create/', views.article_create, name = "create"),
    path(r'update/<id>/', views.article_update, name="update"),
    path(r'delete/<id>/', views.article_delete, name="delete"),
    path(r'<slug:slug>/', views.article_detail, name="details"),
]

djangoFirstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),   # Raw string
    path(r'accounts/', include('accounts.urls')),
    path(r'articles/', include('articles.urls')),
    path(r'apiBase/', include('apiBase.urls')),
    path(r'about/', views.About),
    path(r'', views.Home)
]

urlpatterns += staticfiles_urlpatterns()

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/About.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <h1>About Us</h1>
    <p>We love django and we want more work with django</p>
</body>
</html>

templates/Home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
</head>
<body>
    <h1>Home Page</h1>
    <p>Welcome to our website</p>
</body>
</html>

templates/api_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
</head>
<body>
    <h1>Hello world</h1>
</body>
</html>

templates/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create a New Article</h2>
    </div>
{% endblock %}

templates/article_details.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{article.thumb.url}}">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>

{% endblock %}

templates/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <!-- <h1>Articles lists will display here</h1> -->
    <div class="articles">
        {% for article in articles %}
        <!-- <p>Hello test</p> -->
        <div class="article">
            <h2><a href="{% url 'articles:details' slug=article.slug %}">{{article.title}}</a></h2>
            <p>{{article.snippet}}</p>
            <p>{{article.date}}</p>
            
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base_layout.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Articles</title>
    <link rel="stylesheet" href= "{% static 'styles.css' %}">
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo(1).png' %}"></a></h1>
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

templates/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="signup-form" action="/accounts/login/" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

templates/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="signup-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Signup">
    </form>
{% endblock %}